import { getAdminStorage } from '@/lib/firebase-admin';

const NANO_BANANA_PRO_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent';

// Helper: call Gemini Nano Banana Pro and upload to Firebase Storage
async function callGeminiImage(prompt: string, storagePath: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY manquant dans .env.local');
  }

  const response = await fetch(`${NANO_BANANA_PRO_URL}?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Erreur Gemini API (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const parts = data.candidates?.[0]?.content?.parts;

  if (!parts || parts.length === 0) {
    throw new Error('Aucune image générée par Gemini');
  }

  const imagePart = parts.find(
    (p: { inlineData?: { mimeType: string; data: string } }) =>
      p.inlineData?.mimeType?.startsWith('image/')
  );

  if (!imagePart?.inlineData?.data) {
    throw new Error('Aucune image trouvée dans la réponse Gemini');
  }

  const mimeType: string = imagePart.inlineData.mimeType;
  const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');
  const ext = mimeType === 'image/jpeg' ? 'jpg' : 'png';
  const fullPath = `${storagePath}.${ext}`;

  // Upload to Firebase Storage
  const bucket = getAdminStorage();
  const file = bucket.file(fullPath);

  await file.save(imageBuffer, {
    metadata: { contentType: mimeType },
  });

  await file.makePublic();

  const bucketName = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
  return `https://storage.googleapis.com/${bucketName}/${fullPath}`;
}

/**
 * Generate a blog article banner/cover image using Gemini Nano Banana Pro.
 * Uploads to Firebase Storage and returns the public URL.
 */
export async function generateArticleImage(
  title: string,
  excerpt: string,
  slug: string
): Promise<string> {
  const prompt = buildCoverPrompt(title, excerpt);
  return callGeminiImage(prompt, `images/blog/${slug}`);
}

/**
 * Generate an inline illustration image for use within an article.
 * @param prompt  Descriptive prompt (generated by Claude)
 * @param filename  Filename without extension (e.g. "mon-article-1")
 */
export async function generateInlineImage(
  prompt: string,
  filename: string
): Promise<string> {
  const fullPrompt = buildInlinePrompt(prompt);
  return callGeminiImage(fullPrompt, `images/blog/${filename}`);
}

function buildCoverPrompt(title: string, excerpt: string): string {
  return `Generate a professional, modern blog banner image for the following article. Wide format (16:9 aspect ratio), visually striking, suitable as a hero/cover image for a tech blog.

Article title: "${title}"
Article summary: "${excerpt}"

Style requirements:
- Modern, premium aesthetic with clean lines
- Dark/moody atmosphere with warm accent colors (teal, orange, green tones)
- Abstract or conceptual — do NOT include any text, logos, or watermarks
- Professional photography or 3D render style
- Technology company focused on interactive displays, VR, AI, and collaboration
- High contrast, cinematic lighting
- No people's faces, no stock photo feel

Generate the image only, no text in the response.`;
}

function buildInlinePrompt(description: string): string {
  return `Generate a professional editorial photograph or illustration for a technology blog article. The image should be used inline within the article body.

Scene description: "${description}"

Style requirements:
- Real-world photography style (not AI art look)
- Natural, editorial feel — bright, clean composition
- Modern workplace or technology environment
- No text, no logos, no watermarks in the image
- Professional quality, magazine-worthy
- Warm tones, good lighting, realistic depth of field

Generate the image only, no text in the response.`;
}
