import { getAdminStorage } from '@/lib/firebase-admin';

const NANO_BANANA_2_URL =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-image-preview:generateContent';

// Helper: call Gemini Nano Banana Pro and upload to Firebase Storage
async function callGeminiImage(prompt: string, storagePath: string): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY manquant dans .env.local');
  }

  const response = await fetch(`${NANO_BANANA_2_URL}?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
      },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Erreur Gemini API (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const parts = data.candidates?.[0]?.content?.parts;

  if (!parts || parts.length === 0) {
    throw new Error('Aucune image générée par Gemini');
  }

  const imagePart = parts.find(
    (p: { inlineData?: { mimeType: string; data: string } }) =>
      p.inlineData?.mimeType?.startsWith('image/')
  );

  if (!imagePart?.inlineData?.data) {
    throw new Error('Aucune image trouvée dans la réponse Gemini');
  }

  const mimeType: string = imagePart.inlineData.mimeType;
  const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');
  const ext = mimeType === 'image/jpeg' ? 'jpg' : 'png';
  const fullPath = `${storagePath}.${ext}`;

  // Upload to Firebase Storage
  const bucket = getAdminStorage();
  const file = bucket.file(fullPath);

  await file.save(imageBuffer, {
    metadata: { contentType: mimeType },
  });

  await file.makePublic();

  const bucketName = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
  return `https://storage.googleapis.com/${bucketName}/${fullPath}`;
}

/**
 * Generate a blog article banner/cover image using Gemini Nano Banana Pro.
 * Uploads to Firebase Storage and returns the public URL.
 */
export async function generateArticleImage(
  title: string,
  excerpt: string,
  slug: string
): Promise<string> {
  const prompt = buildCoverPrompt(title, excerpt);
  return callGeminiImage(prompt, `images/blog/${slug}`);
}

/**
 * Generate an inline illustration image for use within an article.
 * @param prompt  Descriptive prompt (generated by Claude)
 * @param filename  Filename without extension (e.g. "mon-article-1")
 */
export async function generateInlineImage(
  prompt: string,
  filename: string
): Promise<string> {
  const fullPrompt = buildInlinePrompt(prompt);
  return callGeminiImage(fullPrompt, `images/blog/${filename}`);
}

function buildCoverPrompt(title: string, excerpt: string): string {
  return `Create a wide-format editorial photograph (16:9) for a professional blog article. The image must feel like a real photograph taken by a skilled photographer — NOT a 3D render, NOT a CGI illustration, NOT generic stock imagery.

Article: "${title}"
Summary: "${excerpt}"

Instructions:
1. READ the article topic carefully and choose an appropriate real-world scene that visually tells the story. Examples:
   - AI / automation article → person working at a clean desk, hands on keyboard, soft natural light from a window, shallow depth of field
   - Collaboration / meetings → two or three people around a table, seen from behind or 3/4 angle, lively body language, a modern office
   - Retail / customer experience → a real store aisle or showroom with warm ambient light, product displays in the background
   - VR / immersive tech → someone wearing a headset in a bright, open space (not dark) — show wonder, not dystopia
   - Business strategy → close-up of hands on a notepad or whiteboard, natural textures, candid feel

2. PHOTOGRAPHY STYLE — choose the most appropriate for the topic:
   - Documentary / editorial: natural light, candid moments, authentic textures
   - Architectural / product: clean geometry, precise framing, calm atmosphere
   - Lifestyle: warm golden light, shallow depth of field, human presence implied
   - Corporate reportage: real offices, real people (backs or silhouettes only), no posed feel

3. AVOID at all costs:
   - Dark backgrounds with floating glowing 3D objects
   - Blue/teal/neon color grading
   - Sci-fi CGI aesthetics
   - Generic stock photo compositions (handshakes, suits pointing at charts)
   - Any text, logos, watermarks, or UI elements in the image

4. MAKE IT SPECIFIC to this article. A "collaboration" article and an "AI" article should produce visually distinct images.

Generate the image only, no text in the response.`;
}

function buildInlinePrompt(description: string): string {
  return `Create an editorial photograph to illustrate a specific moment or concept within a professional blog article.

Scene: "${description}"

The image must look like a real photograph — natural lighting, authentic environment, genuine textures. Think: shot by a photojournalist or a high-end magazine photographer on assignment.

Guidelines:
- Choose a specific, concrete scene that SHOWS the concept rather than symbolising it abstractly
- Real environment: office, workshop, street, showroom — whatever fits the scene
- Human presence where relevant: hands, silhouettes, backs of people — never faces
- Natural, varied lighting: could be morning light, office overhead, window backlight — whatever serves the mood
- Candid, unposed feel — something is actually happening in the frame
- Interesting composition: rule of thirds, leading lines, foreground/background relationship
- Avoid: dark glowing 3D renders, neon colors, floating abstract shapes, hollow tech clichés
- No text, no logos, no watermarks

Generate the image only, no text in the response.`;
}
